name: roulette_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-56.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.3.8
  flutter_animator: 3.2.0
  flutter_fortune_wheel: ^1.1.1
  audioplayers: ^0.20.1
  glassmorphism: ^3.0.0
  shared_preferences: ^2.0.9
  enum_to_string: ^2.0.1
  modal_bottom_sheet: ^2.0.0
  flutter_sliding_tutorial: ^1.1.0+1
  flutter_native_splash: ^1.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/drum_sound.mp3
    - assets/background.jpeg
    - assets/background2.jpeg
    - assets/tutorial1.gif
    - assets/tutorial2.gif

flutter_native_splash:
  image: "assets/icon.png"
  color: "4D79EB"
